export enum RideType {
  ONE_WAY = 'ONE_WAY',
  ROUND_TRIP = 'ROUND_TRIP',
  OUTSTATION = 'OUTSTATION',
  DAILY = 'DAILY',
}

export enum ServiceType {
  DRIVER_ONLY = 'DRIVER_ONLY',
  CAB_WITH_DRIVER = 'CAB_WITH_DRIVER',
}

export enum TripStatus {
  REQUESTED = 'REQUESTED',
  LIVE = 'LIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  MID_CANCELLED = 'MID_CANCELLED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum CancelReason {
  USER_CANCELLED = 'USER_CANCELLED',
  DRIVER_CANCELLED = 'DRIVER_CANCELLED',
  ADMIN_CANCELLED = 'ADMIN_CANCELLED',
  CAR_BREAKDOWN = 'CAR_BREAKDOWN',
  ACCIDENT = 'ACCIDENT',
  NO_SHOW = 'NO_SHOW',
  PAYMENT_ISSUE = 'PAYMENT_ISSUE',
  OTHER = 'OTHER',
}

export enum CancelBy {
  USER = 'USER',
  DRIVER = 'DRIVER',
  ADMIN = 'ADMIN',
  SYSTEM = 'SYSTEM',
}

export enum ChangeType {
  SCHEDULE_TIME = 'SCHEDULE_TIME',
  PICKUP_LOCATION = 'PICKUP_LOCATION',
  DROP_LOCATION = 'DROP_LOCATION',
  RIDE_TYPE = 'RIDE_TYPE',
  SERVICE_TYPE = 'SERVICE_TYPE',
  CANCELLED = 'CANCELLED',
  RESCHEDULED = 'RESCHEDULED',
}

export enum ChangeBy {
  USER = 'USER',
  DRIVER = 'DRIVER',
  ADMIN = 'ADMIN',
  SYSTEM = 'SYSTEM',
}
